<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="robots" content="noindex, nofollow">

        <title><?= $this->configuration->get('app.title') ?></title>
        <!-- JQuery -->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <!-- Validation -->
        <script src="<?= $this->configuration->get('url.root') ?>/assets/js/validation/jquery.validate.min.js"></script>
        <script src="<?= $this->configuration->get('url.root') ?>/assets/js/validation/additional-methods.min.js"></script>
        <!-- Custom JQuery -->
        <script src="<?= $this->configuration->get('url.root') ?>/assets/js/main.js"></script>

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="<?= $this->configuration->get('url.root') ?>/assets/css/vendor/bootstrap.min.css">

        <!-- Optional theme -->
        <link rel="stylesheet" href="<?= $this->configuration->get('url.root') ?>/assets/css/flat-ui.min.css">

        <!-- Latest compiled and minified JavaScript -->
        <script src="<?= $this->configuration->get('url.root') ?>/assets/js/bootstrap.min.js"></script>    
        <script src="<?= $this->configuration->get('url.root') ?>/assets/js/flat-ui.min.js"></script>    
    </head>

    <body>
        <div class="container">
            <div class="row">
                <div class="col-lg-10">
                    <h1><?= $this->configuration->get('app.title') ?></h1>
                </div>
                <div class="col-lg-2">
                    <a class="fresh-logo" style="float: right;" href="<?= $this->createUrl('') ?>">
                        <img src="<?= $this->configuration->get('url.root') ?>/assets/img/logo.png" alt="<?= $this->configuration->get('app.title') ?>" title="<?= $this->configuration->get('app.title') ?>" style="margin-top: 25px;"/>
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <?php require("menu.phtml") ?>
                </div>
            </div>

            <?php require($content) ?>

            <div class="row">
                <div class="col-lg-12">
                    <?php if ($this->configuration->get('dev.debug') == true): ?>
                        <?php //d($this); ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </body>
</html>
