<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="robots" content="noindex, nofollow">

        <title><?= $this->configuration->get('app.title') ?></title>
        <!-- JQuery -->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <!-- Validation -->
        <script src="<?= $this->configuration->get('url.root') ?>/assets/js/validation/jquery.validate.min.js"></script>
        <script src="<?= $this->configuration->get('url.root') ?>/assets/js/validation/additional-methods.min.js"></script>
        <!-- Custom JQuery -->
        <script src="<?= $this->configuration->get('url.root') ?>/assets/js/main.js"></script>

        <link rel="stylesheet" href="<?= $this->configuration->get('url.root') ?>/assets/css/normalize.css"/>

        <!-- FreshFramework CSS -->
        <link rel="stylesheet" href="<?= $this->configuration->get('url.root') ?>/assets/css/style.css"/>

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>    
    </head>

    <body>
        <div class="container">
            <div class="fresh-header">
                <a class="fresh-logo" href="<?= $this->createUrl('') ?>">
                    <img src="<?= $this->configuration->get('url.root') ?>/assets/img/logo.png" alt="<?= $this->configuration->get('app.title') ?>" title="<?= $this->configuration->get('app.title') ?>"/>
                </a>
                <h1><?= $this->configuration->get('app.title') ?></h1>
            </div>

            <nav class="navbar navbar-default">
                <div class="container">
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li class="<?= ($this->action === 'home' ? "active" : "") ?>"><a href="<?= $this->createUrl('') ?>"><?= __Home ?></a></li>
                            <li class="<?= ($this->action === 'user/overview' ? "active" : "") ?>"><a href="<?= $this->createUrl('user/overview') ?>"><?= __User_overview ?></a></li>
                            <li class="<?= ($this->action === 'information' ? "active" : "") ?>"><a href="<?= $this->createUrl('information') ?>"><?= __Information ?></a></li>
                            <li class="<?= ($this->action === 'contact' ? "active" : "") ?>"><a href="<?= $this->createUrl('contact') ?>"><?= __Contact ?></a></li>

                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><?= __Dropdown ?> <span class="caret"></span></a>

                                <ul class="dropdown-menu" role="menu">
                                    <li class="<?= ($this->action === 'test' ? "active" : "") ?>"><a href="<?= $this->createUrl('test') ?>"><?= __Test ?></a></li>
                                    <li><a href="#"><?= __Action ?></a></li>
                                    <li><a href="#"><?= __Action ?></a></li>
                                    <li class="divider"></li>
                                    <li><a href="#"><?= __Action ?></a></li>
                                    <li class="divider"></li>
                                    <li><a href="#"><?= __Action ?></a></li>
                                </ul>

                            </li>

                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </nav>

            <?php require($content) ?>

            <?php if ($this->configuration->get('dev.debug') == true): ?>
                <?php //d($this); ?>
            <?php endif; ?>
        </div>
    </body>
</html>
