<p>
<div class="fresh-remark">
    <?= __Fields_marked_with_are_required ?>
</div>
</p>
<div class="fresh-form">
    <form method="post" action="" id="contact-form">
        <div class="input-element">
            <label for="firstname">
                <?= __First_name ?>*
            </label>
            <input type="text" name="firstname" value="<?= $this->contact->getValue('firstname') ?>" class='required' />
        </div>

        <div class="input-element">
            <label for="insertion">
                <?= __Insertion ?>
            </label>
            <input type="text" name="insertion" value="<?= $this->contact->getValue('insertion') ?>" />
        </div>

        <div class="input-element">
            <label for="surname">
                <?= __Surname ?>*
            </label>
            <input type="text" name="surname" value="<?= $this->contact->getValue('surname') ?>" class='required' />
        </div>

        <div class="input-element">
            <label for="email">
                <?= __Email_address ?>*
            </label>
            <input type="text" name="email" value="<?= $this->contact->getValue('email') ?>" class='required email'/>
        </div>

        <div class="input-element">
            <label for="message">
                <?= __Message ?>*
            </label>
            <textarea name="message" class='required' ><?= $this->contact->getValue('message') ?></textarea>
        </div>

        <div class="input-element">
            <label for="submit">

            </label>
            <input type="submit" name="submit" class="btn btn-default" value="<?= __Send ?>" />
        </div>
    </form>
</div>