<div class="row">
    <div class="col-lg-12">
        <h2>Information</h2>
    </div>
    <div class="col-lg-8">
        FreshFramework makes use of Bootstrap and Kint.
        <h2>Fancy messages</h2>
        <div class="alert alert-success" role="alert">
            Example <strong>success</strong> message
        </div> 
        <div class="alert alert-danger" role="alert">
            Example <strong>error</strong> message
        </div> 
    </div>
    <div class="col-lg-4">
        <h2>Progress bars</h2>
        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;"><span class="sr-only">60% Complete</span></div>
        </div>
    </div>
</div>

