<p>
    <?= __Welcome ?> <?= $this->configuration->get('dev.version') ?>

</p>
<p>
    <strong>What is it</strong><br/>
    FreshFramework is a small pet project. It is a PHP/mySQL framework I've written. It's object oriented, using the MVC (Model, View, Controller) structure, giving the backend programmer a small base to rapidly develop large database-driven web-applications.
</p>
<p>
    It will most likely only be of use for other webdevelopers, but feel free to look around!
</p>
<p>
    <strong>Current state</strong><br/>
    It can read and write from the database, interpret GET and POST parameters and manage sessions. Soon it will be possible to extend a protected class, so a login an registration section can easily be developed within FreshFramework.
</p>
<p>
    Everything in this deployment contains example pages and example user data from the database.
</p>
<p>
    <strong>FreshFramework source and download</strong><br/>
    <a href='https://github.com/arjenschumacher/freshFramework' target='_blank'>https://github.com/arjenschumacher/freshFramework</a>
</p>

